export const CHANGE_LAB="CHANGE_LAB"
export const GET_LABS_SUCCESS="GET_LABS_SUCCESS"

export const GET_PATIENTS_SUCCESS="GET_PATIENTS_SUCCESS"

export const ADD_TO_STORE="ADD_TO_STORE"
export const REMOVE_FROM_STORE="REMOVE_FROM_STORE"

export const CREATE_PATIENT_SUCCESS="CREATE_PATIENT_SUCCESS"
export const UPDATE_PATIENT_SUCCESS="UPDATE_PATIENT_SUCCESS"
export const SORT_DATES="SORT_DATES"
export const DELETE_PATIENT="DELETE_PATIENT"
export const DELETE_PATIENT_SUCCESS="DELETE_PATIENT_SUCCESS"